name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write  # 권한 부여

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 클론
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # 깃헙액션이 자동으로 세팅하는 토큰(별도 변수 세팅 불필요))

      # 2. 모든 브랜치 정보 가져오기
      - name: Fetch all branches
        run: git fetch --all

      # 3. KimDongJun 브랜치 업데이트
      - name: Sync with KimDongJun
        run: |
          git config --global user.name "kimD0ngjun"
          git config --global user.email "chickentasty0112@gmail.com"
          git checkout KimDongJun
          git pull origin KimDongJun
          git pull origin main
          git push origin KimDongJun

      # 4. SongAhream 브랜치 업데이트
      - name: Sync with SongAhream
        run: |
          git checkout SongAhream
          git pull origin SongAhream
          git pull origin main
          git push origin SongAhream
