name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 클론
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}

      # 2. 모든 브랜치 정보 가져오기
      - name: Fetch all branches
        run: git fetch --all

      # 3. KimDongJun 브랜치 업데이트
      - name: Sync with KimDongJun
        run: |
          git config --global user.name "kimD0ngjun"
          git config --global user.email "chickentasty0112@gmail.com"
          git checkout KimDongJun
          git pull origin KimDongJun
          git pull origin main
          git push origin KimDongJun

      # 4. SongAhreum 브랜치 업데이트
      - name: Sync with SongAhreum
        run: |
          git checkout SongAhreum || git checkout -b SongAhreum origin/SongAhreum
          git pull origin SongAhreum
          git pull origin main
          git push origin SongAhreum
